/*
 * Camera API
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AECompensationInfo;
import io.swagger.client.model.AECompensationValue;
import io.swagger.client.model.AELockInfo;
import io.swagger.client.model.AELockValue;
import io.swagger.client.model.FocusModeInfo;
import io.swagger.client.model.FocusModeValue;
import io.swagger.client.model.ISOInfo;
import io.swagger.client.model.ISOValue;
import io.swagger.client.model.Setting;
import io.swagger.client.model.SettingInfo;
import io.swagger.client.model.SettingValue;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Get image.
     *
     * Retrieve the current camera image.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void imageGetTest() throws ApiException {
        byte[] response = api.imageGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsAECOMPENSATIONGetTest() throws ApiException {
        AECompensationInfo response = api.settingsAECOMPENSATIONGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsAECOMPENSATIONPutTest() throws ApiException {
        AECompensationValue body = null;
        api.settingsAECOMPENSATIONPut(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsAELOCKGetTest() throws ApiException {
        AELockInfo response = api.settingsAELOCKGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsAELOCKPutTest() throws ApiException {
        AELockValue body = null;
        api.settingsAELOCKPut(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsFOCUSMODEGetTest() throws ApiException {
        FocusModeInfo response = api.settingsFOCUSMODEGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsFOCUSMODEPutTest() throws ApiException {
        FocusModeValue body = null;
        api.settingsFOCUSMODEPut(body);

        // TODO: test validations
    }
    
    /**
     * Get settings.
     *
     * Retrieve a set of the exposed settings of the camera.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsGetTest() throws ApiException {
        List<Setting> response = api.settingsGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsISOGetTest() throws ApiException {
        ISOInfo response = api.settingsISOGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsISOPutTest() throws ApiException {
        ISOValue body = null;
        api.settingsISOPut(body);

        // TODO: test validations
    }
    
    /**
     * Get setting info.
     *
     * Retrieve information about the specified setting.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsSettingGetTest() throws ApiException {
        String setting = null;
        SettingInfo response = api.settingsSettingGet(setting);

        // TODO: test validations
    }
    
    /**
     * Set setting value.
     *
     * Update the value of the specified setting. Refer to /settings/{setting} for the valid values of the specified setting. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsSettingPutTest() throws ApiException {
        String setting = null;
        SettingValue body = null;
        api.settingsSettingPut(setting, body);

        // TODO: test validations
    }
    
}
