---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "Camera API"
  contact: {}
basePath: "/camera"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"


definitions:

  Setting:
    type: "string"
    enum: &Setting
      - "ISO"
      - "FOCUS_MODE"
      - "AE_COMPENSATION"
      - "AE_LOCK"

  BaseSettingInfo:
    type: object
    properties:
      setting:
        $ref: "#/definitions/Setting"
      editable:
        type: "boolean"
        description: "Specifies whether the value of the setting can be edited."
    required:
      - setting
      - editable

  SettingInfo:
    allOf:
      - $ref: '#/definitions/BaseSettingInfo'
      - type: object
        required:
          - value
          - values
        properties:
          value:
            type: "string"
          values:
            type: "array"
            items:
              type: "string"

  SettingValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: "string"
        description: "The setting value."

  ISO:
    type: integer
    minimum: 0
    exclusiveMinimum: true

  ISOInfo:
    allOf:
      - $ref: '#/definitions/BaseSettingInfo'
      - type: object
        required:
          - value
          - values
        properties:
          value:
            $ref: "#/definitions/ISO"
          values:
            type: "array"
            items:
              $ref: '#/definitions/ISO'

  ISOValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        $ref: "#/definitions/ISO"

  FocusMode:
    type: "string"
    enum:
      - MANUAL
      - AUTO
      - MACRO
      - CONTINUOUS
      - EDF

  FocusModeInfo:
    allOf:
      - $ref: '#/definitions/BaseSettingInfo'
      - type: object
        required:
          - value
          - values
        properties:
          value:
            $ref: "#/definitions/FocusMode"
          values:
            type: "array"
            items:
              $ref: "#/definitions/FocusMode"

  FocusModeValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        $ref: "#/definitions/FocusMode"

  AECompensationInfo:
    allOf:
      - $ref: '#/definitions/BaseSettingInfo'
      - type: object
        required:
          - value
          - values
        properties:
          value:
            type: number
          values:
            type: "array"
            items:
              type: number

  AECompensationValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: number


  AELockInfo:
    allOf:
      - $ref: '#/definitions/BaseSettingInfo'
      - type: object
        required:
          - value
          - values
        properties:
          value:
            type: boolean
          values:
            type: "array"
            items:
              type: boolean


  AELockValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: boolean


paths:

  /image:
    get:
      summary: "Get image."
      description: "Retrieve the current camera image."
      produces:
        - "image/jpeg"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "string"
            format: "binary"
            description: "The current camera image."
  /settings:
    get:
      summary: "Get settings."
      description: "Retrieve a set of the exposed settings of the camera."
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            description: "Set of the exposed settings of the camera."
            items:
              $ref: "#/definitions/Setting"

  /settings/{setting}:
    parameters:
      - name: "setting"
        in: "path"
        required: true
        type: "string"
        enum: *Setting

    get:
      summary: "Get setting info."
      description: "Retrieve information about the specified setting."
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/SettingInfo"
        404:
          description: "The specified setting is not available."

    put:
      summary: "Set setting value."
      description: "Update the value of the specified setting.\nRefer to /settings/{setting}\
        \ for the valid values of the specified setting.\n"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/SettingValue"
      responses:
        204:
          description: "The setting value has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."

  /settings/ISO:

    get:
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/ISOInfo"
        404:
          description: "The specified setting is not available."

    put:
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/ISOValue"
      responses:
        204:
          description: "The setting has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."

  /settings/FOCUS_MODE:

    get:
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/FocusModeInfo"
        404:
          description: "The specified setting is not available."

    put:
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/FocusModeValue"
      responses:
        204:
          description: "The setting has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."

  /settings/AE_COMPENSATION:

    get:
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/AECompensationInfo"
        404:
          description: "The specified setting is not available."

    put:
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/AECompensationValue"
      responses:
        204:
          description: "The setting has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."

  /settings/AE_LOCK:

    get:
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/AELockInfo"
        404:
          description: "The specified setting is not available."

    put:
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/AELockValue"
      responses:
        204:
          description: "The setting has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."